services:
  - type: web
    name: semantic-search-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: COHERE_API_KEY
        sync: false
